set mouse=a
set autoindent
set relativenumber
set number
set nowrap

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()

let g:go_def_mode='gopls'
let g:go_info_mode='gopls'

let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['golint', 'govet']

autocmd FileType go setlocal omnifunc=go#complete#Complete
autocmd FileType go inoremap <buffer> <C-@> <C-x><C-o>

